#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
--------------------------------------------------------------------------------------

### Parameters Visualization ###

This script loads the analysis output files generated by IDM_model and creates plots
to visualize the distribution. We will use the distribution of these parameters to 
inform our selection of parameters in the model_simulation project 

Inputs: 
  	user-specified paths to analysis spreadsheets that result from IDM_model, e.g.: 
  		/Users/pizarror/mturk/idm_data/batch_output/bonus2/bonus2_CDD_analysis.csv
  		/Users/pizarror/mturk/idm_data/batch_output/bonus2/bonus2_CDD_analysis_alpha.csv
  		/Users/pizarror/mturk/idm_data/batch_output/bonus2/bonus2_CRDM_analysis.csv
  		/Users/pizarror/mturk/idm_data/batch_output/SDAN/SDAN_CRDM_analysis.csv

Outputs: 
  	plots of the distribution of the each parameter. For CDD, we will have plots, 
  		likely histograms, for gamma (inverse temperature), kappa (discount rate).
  		For CRDM, we will have histogram plots for alpha (risk aversion), beta 
  		(ambiguity aversion), and gamma (inverse temperature).

Usage: $ python parameters_visualization.py

--------------------------------------------------------------------------------------
"""

# Built-in/Generic Imports
import os,sys

# Libs
import pandas as pd


__author__ = 'Ricardo Pizarro'
__copyright__ = 'Copyright 2023, Introspection and decision-making (IDM) project'
__credits__ = ['Ricardo Pizarro, Silvia Lopez-Guzman']
__license__ = 'IDM_model 1.0'
__version__ = '0.1.0'
__maintainer__ = 'Ricardo Pizarro'
__email__ = 'ricardo.pizarro@nih.gov, silvia.lopezguzman@nih.gov'
__status__ = 'Dev'




def main():
	print('Welcome to parameters visualization, lets get started')



if __name__ == "__main__":
	# main will be executed after running the script
    main()




